"use client";

import { cn } from "@/lib/utils";
import { CategoryTypes } from "@/types";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Container } from "./UI/container";

interface CategoryNavProps {
  data: CategoryTypes[];
}

export const CategoryNav: React.FC<CategoryNavProps> = ({ data }) => {
  const pathname = usePathname();

  const AutoGeneratedRoutes = data.map((route) => ({
    href: `/category/${route.id}`,
    label: route.name,
    active: pathname === `/category/${route.id}`,
  }));

  const routes = [
    {
      href: `/product`,
      label: `Products`,
      active: pathname === `/product`,
    },
    ...AutoGeneratedRoutes,
  ];

  return (
    <Container>
      <nav className="flex justify-center lg:mt-4 items-center space-x-4 lg:space-x-6 flex-wrap mx-auto">
        {routes.map((route: any) => (
          <Link
            key={route.href}
            href={route.href}
            className={cn(
              "text-sm font-medium bg-sky-400/25 text-center mt-2 hover:bg-sky-400/20 hover:text-black p-2 rounded-2xl transition-colors",
              route.active
                ? "text-black bg-sky-400/75 hover:bg-sky-400/75 shadow"
                : null
            )}
          >
            {route.label}
          </Link>
        ))}
      </nav>
    </Container>
  );
};
